[default]
project_name = ""
version = ""
debug = false

[default.database]
host = ""
port = 5432
username = ""
name = ""

[default.auth]
access_token_expire_minutes = 43200  # 30 дней

[local]
debug = true

[local.database]
host = ""
port = 5432
username = ""
name = ""

[docker]
debug = false

[docker.database]
host = ""
port = 5432
username = ""
name = ""